include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
    lines_longer_than_80_chars: ignore
    omit_local_variable_types: ignore
    public_member_api_docs: ignore
    strict_raw_type: ignore
    avoid_dynamic_calls: ignore
    argument_type_not_assignable: ignore
    avoid_redundant_argument_values: ignore

linter:
  rules:
    always_use_package_imports: true
